name: ROS2 Node Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: ["3.11"]
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root
